Added burst count licenses & total cost for used licenses fields to O365 Bill model
ilanddev/javascript-sdk pull request #591
Opened 2021-06-16 21:03 UTC by Juchazari

https://us-east-1.api.ilandcloud.com/doc/current/#/Companies/getO365BillingHistory

2021-06-18 18:20 UTC, iamtash requested changes
'Added' --> 'Add' in the commit message. the general convention is to keep the action/verb in a commit message (e.g., add, upgrade, fix, remove, refactor) in the present tense.

2021-06-18 18:20 UTC, iamtash commented on src/sdk/model/company/o365-bill.ts
> +   */
`@returns` doc

2021-06-18 18:20 UTC, iamtash commented on src/sdk/model/company/o365-bill.ts
> +   */
`@returns` doc

2021-06-21 14:26 UTC, Juchazari commented
@iamtash I should have asked before pushing updates, but there are multiple methods without return doc, should I add them for those methods as well? Also, like you said it should be `@returns` correct? Because there are two methods I see with one having `@return` and the other having `@returns`.

2021-06-21 16:32 UTC, iamtash commented
> @iamtash I should have asked before pushing updates, but there are multiple methods without return doc, should I add them for those methods as well? Also, like you said it should be `@returns` correct? Because there are two methods I see with one having `@return` and the other having `@returns`.

pretty sure `@return` and `@returns` are synonyms. both are fine for me, i guess as long as within a particular file the tag usage is consistent. yeah if you don't mind filling in the missing docs that'd be great 🙂

2021-06-21 17:54 UTC, iamtash approved these changes

2021-06-22 17:02 UTC, ariquinones approved these changes

2021-06-22 17:02 UTC, merged