Add get vac jobs to user model
ilanddev/javascript-sdk pull request #658
Opened 2022-05-25 18:44 UTC by Vinmanftw

http://doc.10.api.iland.test/1.0/#/Users/getBaJobsForUser 

@JoMas971 @Juchazari @iamtash

2022-06-02 22:27 UTC, iamtash requested changes

2022-06-02 22:27 UTC, iamtash commented on src/sdk/model/user/user.ts
> +  async getVacJobs(companyId: string, location?: string): Promise<Array<BaJob>> {
location --> locationId

2022-06-02 22:27 UTC, iamtash commented on src/sdk/model/user/user.ts
> +   * @param {string} location
location --> locationId

2022-06-14 19:28 UTC, Vinmanftw commented
> i see you opened a duplicate pull request. let me know if you need help pushing updates to this one @Vinmanftw

All good Sorry I had no Idea where to find my old pull request on here or the fact that I had to make changes through github I can see it all now though thank you!

2022-06-15 15:10 UTC, Vinmanftw commented on src/sdk/model/user/user.ts
> +            location: location
I pushed again but I might make some changes because the new hash wasn't working I'm going to see if it does new after pushing

2022-06-15 22:47 UTC, iamtash commented
@Vinmanftw please update the commit message to just "Add get vac jobs endpoint to user resource" since the company_uuid getter was added in a previous PR and we want our commit messages to be as accurate as possible

2022-06-15 22:49 UTC, iamtash requested changes
@Vinmanftw please update the commit message to just "Add get vac jobs endpoint to user resource" since the company_uuid getter was added in a previous PR

2022-06-17 15:29 UTC, merged